spring:
 data.mongodb:
  #uri: mongodb://localhost:27017/gestaohospitaldb
  host: ds229826.mlab.com # hostname
  port: 29826 # port
  database: gestaohospitaldb
  username: gestaohospital
  password: gh123456@@.
  #authentication-database: admin
server:
 port: 9980
