spring:
  data.mongodb:
    host: ds125486.mlab.com # hostname
    port: 25486 # port
    #uri: mongodb://ds125486.mlab.com:25486
    database: gestaohospitaldb
    username: gestaohospital
    password: gh123456@@.
    #authentication-database: admin
